# Small test configuration for quick validation runs
numguys: 50
numfriends: 5
numgroups: 2
numticks: 20
memory: 10
seed: 12345
new_info_mode: "central"
run_dir: "data_test"
measurement_ticks: [5, 10, 15, 19]
